# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Run app
      run: npm install
    - name: Install playwright
      run: npx playwright install
    - name: Run npm tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "Scopi"

  test_ui:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Run app
        run: npm install
      - name: Install playwright
        run: npx playwright install
      - name: Start UI
        run: npm start &
      - name: Wait for UI to start
        run: sleep 10s
      - name: Run npm tests
        run: npm run test:ui
